M48
; DRILL file KiCad 10.0.0 date 2026-04-09T19:38:00
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-09T19:38:00-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.210
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C1.300
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C3.200
%
G90
G05
T1
X93.678Y-163.13
X99.458Y-163.13
T2
X85.852Y-119.888
T3
X72.724Y-156.528
T4
X72.136Y-108.668
X72.136Y-166.668
X167.132Y-166.668
X167.136Y-108.712
M30
